### ISSUE TITLE
environment is ignored

### ISSUE THREAD

**Issue by VojtechFried** [sboulema/RunAsAdmin#2]
I run VS through a .bat file that first sets some environment variables needed for build. When using RusAsAdmin, the environment is lost.

**Comment by sboulema** [comment]
My guess is that the bat file sets the environment variables for your current user and VS runs under the admin user which has its own environment without your variables.

If your are already using a batch file to start VS wouldn't it be easier to not use this extension and start VS as admin with your batch file using [runas](https://www.windows-commandline.com/windows-runas-command-prompt/) ?
