### ISSUE TITLE
Broke my mouse button customization as well as my AutoHotKey settings.

### ISSUE THREAD

**Issue by iVoteSize** [sboulema/RunAsAdmin#3]
I installed this plugin on a whim, more-or-less; but once install neither my mouse middle-button's double-click (via http://Support.Logitech.com/en_us/software/setpoint) nor my AutoHotKey macros (http://AutoHotKey.com) were working... which I use frequently for editing code. I tried disabling and deleting your extension but (Admin) still appeared in the titlebar and I could not get my coding enhancements back. I found http://StackOverflow.com/a/1905257/1424959 and then ran a windows compatibility troubleshooter to set my preferences at windows 8 and now have my titlebar like before and my mouse and keyboard able to fully engage the code... but it would be better if this plugin uninstalled fully as I'm not sure that a windows 8 environment is what's best form my vs2017 project. 

Any advise on if I need to / how to get my vs2017 running without admin privileges and in a win 10 settings is greatly appreciated.

**Comment by iVoteSize** [comment]
Once we're at it, even though I now have my mouse/AutoHotKey working again - I can not drag-and-drop selected text in the editor (I need to cut-paste it, which takes a lot longer and is not preferable)... is there any chance that this issue is related to the one above?

**Comment by sboulema** [comment]
Sad to hear you experienced problems using this extension :(

As documented (https://github.com/sboulema/RunAsAdmin#uninstalling-the-extension), uninstalling or disabling will not stop the effects of the extension. You have to disable running as administrator in the settings dialog of the extension. After that you can uninstall/disable the extension.

My advice would be:
- revert the chages from the troubleshooter and run VS in a win10 environment
- reinstall the RunAsAdmin extension
- disable running as admin from the extensions options dialog
- uninstall the RunAsAdmin extension
