### ISSUE TITLE
SetSite failed for package [RunAsAdminPackage]Source. Is anyone else having this issue?

### ISSUE THREAD

**Issue by stevemesser** [sboulema/RunAsAdmin#4]
SetSite failed for package [RunAsAdminPackage]Source: &apos;Microsoft.VisualStudio.Shell.14.0&apos; 
Description: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result 
or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
&#x000D;&#x000A;System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. 
You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)
&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)
&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.PackageContainer.GetService(Type serviceType)
&#x000D;&#x000A;   at System.ComponentModel.Container.Site.GetService(Type service)
&#x000D;&#x000A;   at System.ComponentModel.Component.GetService(Type service)
&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.get_SettingsMananger()
&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingsFromStorage()
&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.set_Site(ISite value)
&#x000D;&#x000A;   at System.ComponentModel.Container.Add(IComponent component, String name)
&#x000D;&#x000A;   at System.ComponentModel.Container.Add(IComponent component)
&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.GetDialogPage(Type dialogPageType)
&#x000D;&#x000A;   at SamirBoulema.RunAsAdmin.RunAsAdminPackage.&lt;InitializeAsync&gt;d__3.MoveNext()
&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---
&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass16_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()
&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---
&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()

**Comment by sboulema** [comment]
Thanks for reporting!

Updating to the latest release should fix the problem!
https://github.com/sboulema/RunAsAdmin/releases/tag/v1.5.11
